name: Build packages PR

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'packages.sh'
      - '.github/workflows/build-packages.yaml'

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lx01:
    name: LX01
    if: ${{ github.repository == 'duhow/xiaoai-patch' }}
    uses: duhow/xiaoai-patch/.github/workflows/build-packages.yaml@master
    with:
      model: LX01
  lx06:
    name: LX06
    if: ${{ github.repository == 'duhow/xiaoai-patch' }}
    uses: duhow/xiaoai-patch/.github/workflows/build-packages.yaml@master
    with:
      model: LX06
  s12:
    name: S12
    if: contains(github.event.pull_request.labels.*.name, 'S12')
    uses: duhow/xiaoai-patch/.github/workflows/build-packages.yaml@master
    with:
      model: S12
